version: "3.8"

services:
  webapp:
    build:
      context: ./docker/webapp
      dockerfile: Dockerfile
    container_name: webapp_container
    ports:
      - "3000:3000"
    env_file:
      - .env # Loads environment variables from the .env file
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb

  scanner:
    build:
      context: ./docker/scanner
      dockerfile: Dockerfile
    container_name: scanner_container
    ports:
      - "3001:3001"
    env_file:
      - .env # Loads environment variables from the .env file
    volumes:
      - .:/usr/src/scanner
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} # Uses the username from .env
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} # Uses the password from .env
